services:
  postgres:
    image: postgres:15-alpine
    container_name: lovio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lovio_db
      POSTGRES_USER: lovio_user
      POSTGRES_PASSWORD: lovio_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lovio_user -d lovio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local